[build]
# This flag is needed to avoid rustdoc to hang because of infinite recursive type (See Pow implementation)
rustdocflags = ["-Znext-solver"] 

# [build]
# rustdocflags = [ "--html-in-header", "docs/typstts.html" ]
